# Generated by Django 3.0.4 on 2020-03-27 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('time_published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, default=None, max_length=30)),
                ('lastname', models.TextField(blank=True, default=None, max_length=30)),
                ('flat_number', models.CharField(max_length=5)),
                ('number_of_people', models.IntegerField(blank=True, default=None)),
                ('profession', models.TextField(blank=True, default=None, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cleanliness', 'Cleanliness'), ('Parking', 'Parking'), ('Staff', 'Staff'), ('Billing', 'Billing'), ('Residents', 'Residents'), ('Other', 'Other')], max_length=15)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=250)),
                ('time_published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('time_completed', models.DateTimeField(blank=True, default=None)),
                ('isCompleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(default='Miscellaneous', max_length=20)),
                ('description', models.TextField(blank=True, default=None, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
